[directories]
images = { path = "/home/abhi/pics/pictures/images", tree = false }
documents = { path = "/home/abhi/docs/lib", tree = false }
videos = { path = "/home/abhi/videos", tree = true }
archives = { path = "/home/abhi/archive", tree = false }

[input_dirs]
dirs = [
  "/home/abhi/videos",
  "/home/abhi/downloads"
]
